# Generated by Django 5.1 on 2024-09-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id_patient",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=13)),
                ("emergency_contact_number", models.CharField(max_length=13)),
                ("emergency_contact_name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("insu_number", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "patient",
            },
        ),
    ]
