# Generated by Django 5.1 on 2024-09-09 10:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
        ("patient", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                ("id_admission", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_admission",
                    models.CharField(
                        choices=[("planned", "Planned"), ("emergency", "Emergency")],
                        max_length=20,
                    ),
                ),
                (
                    "date_time_admission",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 9, 9, 10, 15, 51, 971934)
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        db_column="doctor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_roles_doctor",
                        to="staff.staff",
                    ),
                ),
                (
                    "id_dept",
                    models.ForeignKey(
                        db_column="id_dept",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        db_column="id_patient",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        db_column="nurse",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_roles_nurse",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "admission",
            },
        ),
        migrations.CreateModel(
            name="EmergencyAdmission",
            fields=[
                (
                    "id_emergency_admission",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("patient_condition", models.TextField()),
                (
                    "id_admission",
                    models.OneToOneField(
                        db_column="id_admission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_admission",
                        to="admission.admission",
                    ),
                ),
                (
                    "triage_nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_nurse_admissions",
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "emergency_admission",
            },
        ),
        migrations.CreateModel(
            name="PlannedAdmission",
            fields=[
                (
                    "id_planned_admission",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("reference_number", models.CharField(max_length=20, unique=True)),
                ("referring_health_practitioner", models.CharField(max_length=50)),
                (
                    "id_admission",
                    models.OneToOneField(
                        db_column="id_admission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_admission",
                        to="admission.admission",
                    ),
                ),
            ],
            options={
                "db_table": "planned_admission",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                ("id_services", models.AutoField(primary_key=True, serialize=False)),
                ("name_of_services", models.CharField(max_length=20)),
                (
                    "services_cost",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "id_admission",
                    models.ForeignKey(
                        db_column="id_admission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.admission",
                    ),
                ),
            ],
        ),
    ]
