# Generated by Django 5.1 on 2024-09-09 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0006_alter_admission_date_time_admission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="date_time_admission",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 9, 10, 24, 45, 499115)
            ),
        ),
        migrations.AlterModelTable(
            name="services",
            table="services",
        ),
    ]
