# Generated by Django 5.1 on 2024-09-09 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id_dept",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "dept_type",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Emergency", "Emergency"),
                            ("Pediatrics", "Pediatrics"),
                            ("Surgery", "Surgery"),
                        ],
                        default="General",
                        max_length=20,
                    ),
                ),
                ("dept_name", models.CharField(default="", max_length=30, unique=True)),
                ("start_time", models.TimeField(default="10:00:00")),
                ("end_time", models.TimeField(default="20:00:00")),
                (
                    "operating_theatre",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
            options={
                "db_table": "department",
            },
        ),
    ]
