# Generated by Django 5.1 on 2024-09-09 10:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wards",
            fields=[
                ("id_wards", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_ward",
                    models.CharField(
                        choices=[("general", "General"), ("ICU", "ICU")], max_length=10
                    ),
                ),
                (
                    "id_dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
            ],
            options={
                "db_table": "wards",
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id_bed",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("comfort_levels", models.CharField(max_length=30)),
                (
                    "bed_length",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(2.13),
                        ]
                    ),
                ),
                (
                    "bed_width",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.01),
                            django.core.validators.MaxValueValidator(1.27),
                        ]
                    ),
                ),
                (
                    "bed_thickness",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(15.24),
                            django.core.validators.MaxValueValidator(17.78),
                        ]
                    ),
                ),
                (
                    "bed_cost",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "id_wards",
                    models.ForeignKey(
                        db_column="id_wards",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wards.wards",
                    ),
                ),
            ],
            options={
                "db_table": "bed",
            },
        ),
    ]
