# Generated by Django 5.1 on 2024-09-09 10:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admission", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id_bill", models.AutoField(primary_key=True, serialize=False)),
                (
                    "total_cost",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50000),
                        ],
                    ),
                ),
                (
                    "cost_covered_insu",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "balanced_owed",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discharge_date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 9, 9, 10, 15, 51, 972582)
                    ),
                ),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "id_admission",
                    models.ForeignKey(
                        db_column="id_admission",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admission.admission",
                    ),
                ),
                (
                    "id_patient",
                    models.ForeignKey(
                        db_column="id_patient",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id_payment", models.AutoField(primary_key=True, serialize=False)),
                ("cc_number", models.CharField(max_length=20)),
                (
                    "expired_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.datetime(2024, 9, 9, 10, 15, 51, 972682)
                            )
                        ]
                    ),
                ),
                ("card_holder_name", models.CharField(max_length=30)),
                (
                    "id_bill",
                    models.ForeignKey(
                        db_column="id_bill",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bill.bill",
                    ),
                ),
            ],
        ),
    ]
