# Generated by Django 5.1 on 2024-09-09 10:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0006_alter_bill_discharge_date_alter_payment_expired_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="discharge_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 9, 10, 24, 45, 500526)
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="expired_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(2024, 9, 9, 10, 24, 45, 500645)
                    )
                ]
            ),
        ),
        migrations.AlterModelTable(
            name="bill",
            table="bill",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="payment",
        ),
    ]
