# Generated by Django 5.1 on 2024-09-09 10:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalSpeciality",
            fields=[
                (
                    "id_medical_speciality",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name_medical_speciality", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "medical_speciality",
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("id_roles", models.AutoField(primary_key=True, serialize=False)),
                ("name_role", models.CharField(max_length=30, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id_staff",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("mobile", models.CharField(max_length=13)),
                (
                    "salary",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "id_dept",
                    models.ForeignKey(
                        db_column="id_dept",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="department.department",
                    ),
                ),
                (
                    "id_roles",
                    models.ForeignKey(
                        db_column="id_roles",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.roles",
                    ),
                ),
            ],
            options={
                "db_table": "staff",
            },
        ),
        migrations.CreateModel(
            name="OwnershipSpeciality",
            fields=[
                ("id_ownership", models.AutoField(primary_key=True, serialize=False)),
                ("level_of_profiency", models.CharField(max_length=30)),
                ("training_date", models.DateField()),
                (
                    "id_medical_speciality",
                    models.ForeignKey(
                        db_column="id_medical_speciality",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.medicalspeciality",
                    ),
                ),
                (
                    "id_staff",
                    models.ForeignKey(
                        db_column="id_staff",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "ownership_speciality",
            },
        ),
        migrations.CreateModel(
            name="WWCC",
            fields=[
                ("wwcc_id", models.AutoField(primary_key=True, serialize=False)),
                ("wwcc_number", models.CharField(max_length=30, unique=True)),
                (
                    "expired_date",
                    models.DateField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.datetime(2024, 9, 9, 10, 15, 51, 971349)
                            )
                        ]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "id_staff",
                    models.ForeignKey(
                        db_column="id_staff",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staff.staff",
                    ),
                ),
            ],
            options={
                "db_table": "wwcc",
            },
        ),
    ]
