# Generated by Django 5.1 on 2024-09-09 10:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_alter_wwcc_expired_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wwcc",
            name="expired_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(2024, 9, 9, 10, 19, 50, 325764)
                    )
                ]
            ),
        ),
    ]
